Name: opengeo-suite-data
Version: 2.4.1
Release: 1
Summary: Sample geospatial data required for use with the OpenGeo Suite.
Group: Unspecified
License: see http://opengeo.org
Requires(post): bash
Requires(preun): bash
Requires: tomcat5
Patch: medford_taxlots_datastore.patch

%define _rpmdir ../ 
%define _rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm 
%define _unpackaged_files_terminate_build 0

%description
A customized GeoServer data directory containing data required for use with 
the OpenGeo Suite.  


%prep
  cd $RPM_SOURCE_DIR/opengeo-suite-data/data_dir
%patch -p1
  cd ../../../

%install
  rm -rf $RPM_BUILD_ROOT
  mkdir -p $RPM_BUILD_ROOT/usr/share/opengeo-suite-data/geoserver_data
  mkdir -p $RPM_BUILD_ROOT/usr/share/opengeo-suite-data/geoexplorer_data
  cp -rp  $RPM_SOURCE_DIR/opengeo-suite-data/data_dir/* $RPM_BUILD_ROOT/usr/share/opengeo-suite-data/geoserver_data/.
  #cp $RPM_SOURCE_DIR/opengeo-suite-data/debian/datastore.xml $RPM_BUILD_ROOT/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Taxlots/datastore.xml
  find $RPM_BUILD_ROOT/usr/share/opengeo-suite-data -iname .svn  -print0 | xargs -0 rm -rf
%post
chown tomcat. /usr/share/opengeo-suite-data -R

%preun

%postun
# remove files
# remove users


%clean

%files
%defattr(-,root,root,-)
%dir "/usr/share/opengeo-suite-data/*"
%dir "/usr/share/opengeo-suite-data/geoexplorer_data/"
"/usr/share/opengeo-suite-data/geoserver_data/data/dem/medford_dem.tif"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/acknowledgements.txt"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_bikelanes.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_bikelanes.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_bikelanes.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_bikelanes.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_buildings.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_buildings.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_buildings.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_buildings.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_citylimits.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_citylimits.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_citylimits.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_citylimits.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_firestations.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_firestations.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_firestations.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_firestations.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hospital.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hospital.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hospital.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hospital.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hydro.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hydro.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hydro.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_hydro.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_library.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_library.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_library.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_library.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_parks.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_parks.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_parks.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_parks.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_police.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_police.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_police.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_police.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_schools.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_schools.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_schools.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_schools.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_stormdrains.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_stormdrains.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_stormdrains.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_stormdrains.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_streets.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_streets.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_streets.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_streets.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_wetlands.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_wetlands.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_wetlands.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_wetlands.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_zoning.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_zoning.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_zoning.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/medford/medford_zoning.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/usa/usa_states.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/usa/usa_states.fix"
"/usr/share/opengeo-suite-data/geoserver_data/data/usa/usa_states.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/usa/usa_states.qix"
"/usr/share/opengeo-suite-data/geoserver_data/data/usa/usa_states.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/usa/usa_states.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/Readme.txt"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_borders.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_borders.fix"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_borders.prj"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_borders.qix"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_borders.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_borders.shx"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_cities.dbf"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_cities.fix"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_cities.qix"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_cities.shp"
"/usr/share/opengeo-suite-data/geoserver_data/data/world/world_cities.shx"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WCS_describeCoverage.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WCS_getCapabilities.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WCS_getCoverage.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_describeFeatureType-1.0.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_describeFeatureType-1.1.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getCapabilities-1.0.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getCapabilities-1.1.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeature-1.0.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeature-1.1.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBBOX-1.0.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBBOX-1.1.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBBOX.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBetween-1.0.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBetween-1.1.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBetween.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureBetweenCQL.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureFid.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureFidFilter.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureIntersects-1.0.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureIntersects-1.1.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureIntersects.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_getFeatureMultiFilter.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_mathGetFeature.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_mathGetFeature.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_transactionDelete.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_transactionInsert.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_transactionUpdate.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WFS_transactionUpdateGeom.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_GetLegendGraphic-SLD.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_GetLegendGraphic-SLD_BODY.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_GetLegendGraphic.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_describeLayer.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_featureInfo.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getCapabilities.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_OpenLayers.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_SLD_BODY_LiteralMode.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_SVG.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_SVG_Style.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_fid.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_fidfilter.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_inlineFeature.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_inlineFeatureSmile.xml"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_multilayer.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_multilayer_cql.url"
"/usr/share/opengeo-suite-data/geoserver_data/demo/WMS_getMap_multilayer_filter.url"
"/usr/share/opengeo-suite-data/geoserver_data/global.xml"
"/usr/share/opengeo-suite-data/geoserver_data/layergroups/Medford.xml"
"/usr/share/opengeo-suite-data/geoserver_data/layergroups/World.xml"
"/usr/share/opengeo-suite-data/geoserver_data/logging.xml"
"/usr/share/opengeo-suite-data/geoserver_data/logs/DEFAULT_LOGGING.properties"
"/usr/share/opengeo-suite-data/geoserver_data/logs/GEOSERVER_DEVELOPER_LOGGING.properties"
"/usr/share/opengeo-suite-data/geoserver_data/logs/GEOTOOLS_DEVELOPER_LOGGING.properties"
"/usr/share/opengeo-suite-data/geoserver_data/logs/PRODUCTION_LOGGING.properties"
"/usr/share/opengeo-suite-data/geoserver_data/logs/VERBOSE_LOGGING.properties"
"/usr/share/opengeo-suite-data/geoserver_data/palettes/dem31.pal"
"/usr/share/opengeo-suite-data/geoserver_data/palettes/ita31.pal"
"/usr/share/opengeo-suite-data/geoserver_data/palettes/ny31.pal"
"/usr/share/opengeo-suite-data/geoserver_data/palettes/popshade.png"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/AddressGap.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/AddressOverlap.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/AngleSize.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/Attribute.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/Constraint.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/ContainsIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/CrossesIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/DisjointIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/Domain.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/Equality.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/GazetteerName.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/IntersectsIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/IsValidGeometry.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineCoveredByFeatureLine.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineCoveredByPolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineCoveredByPolygonBoundary.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineEndPointCoveredByLine.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineIntersectsLineWithNode.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineMustBeASinglePart.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineNoDangles.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineNoPseudoNode.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineNoSelfIntersect.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineNoSelfOverlapping.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LineNotTouchingPolygonInterior.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LinesNotIntersect.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/LinesNotOverlap.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/NameExists.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/NameInList.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/NullZero.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/OverlapsIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PointCoveredByEndPointOfLine.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PointCoveredByLine.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PointCoveredByPolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PointCoveredByPolygonBoundary.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PointInsidePolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonBoundaryCoveredByPolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonCoveredByFeaturePolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonCoveredByPolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonNoGaps.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonNotCoveredByPolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonNotOverlappingLine.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/PolygonNotOverlappingPolygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/Range.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/RelateIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/SQL.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/SingleValue.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/StarNode.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/TouchesIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/UniqueFID.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/Uniquity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/plugIns/WithinIntegrity.xml"
"/usr/share/opengeo-suite-data/geoserver_data/printing/config.yaml"
"/usr/share/opengeo-suite-data/geoserver_data/proxy/proxy.xml"
"/usr/share/opengeo-suite-data/geoserver_data/security/layers.properties"
"/usr/share/opengeo-suite-data/geoserver_data/security/rest.properties"
"/usr/share/opengeo-suite-data/geoserver_data/security/service.properties"
"/usr/share/opengeo-suite-data/geoserver_data/security/users.properties"
"/usr/share/opengeo-suite-data/geoserver_data/styles/OR_23815.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/OR_23818.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/OR_6215.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/OR_6218.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_line.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_line.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_point.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_point.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_polygon.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_polygon.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/default_raster.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/elementary_school.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/elementary_school10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/elementary_school13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/elementary_school16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/elementary_school20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/firebrigade10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/firebrigade13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/firebrigade16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/firebrigade20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/high_school10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/high_school13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/high_school16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/high_school20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/hospital10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/hospital13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/hospital16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/hospital20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/interstate_5.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/interstate_512.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/interstate_515.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/interstate_518.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/interstate_521.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/interstate_524.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/library10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/library13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/library16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/library20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_bikelanes.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_bikelanes.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_buildings.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_buildings.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_citylimits.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_citylimits.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_firestations.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_firestations.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_hospitals.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_hospitals.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_hydro.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_hydro.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_library.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_library.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_parks.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_parks.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_police.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_police.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_schools.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_schools.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_stormdrains.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_stormdrains.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_streets.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_streets.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_taxlots.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_taxlots.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_wetlands.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_wetlands.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_zoning.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/medford_zoning.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/middle_school10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/middle_school13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/middle_school16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/middle_school20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/police10.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/police13.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/police16.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/police20.png"
"/usr/share/opengeo-suite-data/geoserver_data/styles/raster.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/usa_states.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/usa_states.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/world_borders.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/world_borders.xml"
"/usr/share/opengeo-suite-data/geoserver_data/styles/world_cities.sld"
"/usr/share/opengeo-suite-data/geoserver_data/styles/world_cities.xml"
"/usr/share/opengeo-suite-data/geoserver_data/user_projections/epsg.properties"
"/usr/share/opengeo-suite-data/geoserver_data/validation/FeatureCheck.xml"
"/usr/share/opengeo-suite-data/geoserver_data/validation/IntegrityCheck.xml"
"/usr/share/opengeo-suite-data/geoserver_data/wcs.xml"
"/usr/share/opengeo-suite-data/geoserver_data/wfs.xml"
"/usr/share/opengeo-suite-data/geoserver_data/wms.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/default.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Digital Elevation/coveragestore.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Digital Elevation/elevation/coverage.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Digital Elevation/elevation/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/bikelanes/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/bikelanes/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/buildings/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/buildings/height.ftl"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/buildings/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/citylimits/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/citylimits/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/datastore.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/firestations/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/firestations/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/hospitals/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/hospitals/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/hydro/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/hydro/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/libraries/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/libraries/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/parks/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/parks/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/police/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/police/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/schools/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/schools/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/stormdrains/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/stormdrains/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/streets/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/streets/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/wetlands/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/wetlands/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/zoning/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Medford/zoning/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Taxlots/datastore.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Taxlots/taxlots/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/Taxlots/taxlots/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/namespace.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/medford/workspace.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/usa/USA States/datastore.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/usa/USA States/states/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/usa/USA States/states/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/usa/namespace.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/usa/workspace.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/World/borders/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/World/borders/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/World/cities/featuretype.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/World/cities/layer.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/World/datastore.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/namespace.xml"
"/usr/share/opengeo-suite-data/geoserver_data/workspaces/world/workspace.xml"
"/usr/share/opengeo-suite-data/geoserver_data/www/ol-demo.html"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/OpenLayers.js"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/blank.gif"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/close.gif"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/cloud-popup-relative.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/drag-rectangle-off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/drag-rectangle-on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/east-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/layer-switcher-maximize.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/layer-switcher-minimize.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/marker-blue.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/marker-gold.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/marker-green.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/marker.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/measuring-stick-off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/measuring-stick-on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/north-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/panning-hand-off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/panning-hand-on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/slider.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/south-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/west-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/zoom-minus-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/zoom-plus-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/zoom-world-mini.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/img/zoombar.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/ol-demo.cfg"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/readme.txt"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/framedCloud.css"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/add_point_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/add_point_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/blank.gif"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/close.gif"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/drag-rectangle-off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/drag-rectangle-on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/draw_line_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/draw_line_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/draw_point_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/draw_point_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/draw_polygon_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/draw_polygon_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/editing_tool_bar.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/move_feature_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/move_feature_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/overview_replacement.gif"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/pan_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/pan_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/panning-hand-off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/panning-hand-on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/remove_point_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/remove_point_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/view_next_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/view_next_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/view_previous_off.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/img/view_previous_on.png"
"/usr/share/opengeo-suite-data/geoserver_data/www/openlayers/theme/default/style.css"
"/usr/share/opengeo-suite-data/geoserver_data/www/styles/green.sld"
"/usr/share/opengeo-suite-data/geoserver_data/www/styles/remoteOws.sld"
"/usr/share/opengeo-suite-data/geoserver_data/www/styles/remoteTasmania.sld"
"/usr/share/opengeo-suite-data/geoserver_data/www/wfs-t.html"



