#!/bin/bash

set -x

. /usr/share/debconf/confmodule

case "$1" in
  install)
    ;;

  upgrade)
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument '$1'" >&2
    exit 1
    ;;

esac

#DEBHELPER#
