#!/bin/sh

set -e

case "$1" in
remove|upgrade|purge)
    # restart tomcat
    invoke-rc.d tomcat6 restart
    ;;

failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

*)
    echo "postrm called with unknown argument '$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#
